#####
## WARNING
##
## The groups specified here should replicate the groups in the Eschercloud IPA appliance environments
##
## https://github.com/stackhpc/ansible-slurm-appliance/blob/main/environments/common/inventory/groups
## https://github.com/stackhpc/ansible-slurm-appliance/blob/main/environments/common/layouts/everything
#####
# These groups should represent the everything layout
ipa_cluster_groups_required:
  ipaprimary:     ["{{ ipa_cluster_name }}_primary"]
  ipareplicas:     ["{{ ipa_cluster_name }}_replica"]


# These are the additional groups required for monitoring (see everything layout)
#ipa_cluster_groups_monitoring:
#  podman:        [opensearch, filebeat, mysql]
#  prometheus:    [control]
#  grafana:       [control]
#  alertmanager:  [control]
#  node_exporter: [cluster]
#  opensearch:    [control]
#  slurm_stats:   [control]
#  filebeat:      [slurm_stats]

#ipa_cluster_deploy_ssh_keys_extra: []

# List of hw_scsi_models that result in block devices presenting as /dev/sdX
# rather than /dev/vdX
scsi_models:
  # Ceph [https://docs.ceph.com/en/quincy/rbd/rbd-openstack/#image-properties]
  - virtio-scsi
ipa_cluster_floating_ips_wanted: yes