#####
## WARNING
##
## The groups specified here should replicate the groups in the Eschercloud IPA appliance environments
##
## https://github.com/stackhpc/ansible-slurm-appliance/blob/main/environments/common/inventory/groups
## https://github.com/stackhpc/ansible-slurm-appliance/blob/main/environments/common/layouts/everything
#####
# These groups should represent the everything layout
ipa_cluster_groups_required:
  ipaprimary:     ["{{ ipa_cluster_name }}_primary"]
  ipareplicas:     ["{{ ipa_cluster_name }}_replica"]


# These are the additional groups required for monitoring (see everything layout)
#ipa_cluster_groups_monitoring:
#  podman:        [opensearch, filebeat, mysql]
#  prometheus:    [control]
#  grafana:       [control]
#  alertmanager:  [control]
#  node_exporter: [cluster]
#  opensearch:    [control]
#  slurm_stats:   [control]
#  filebeat:      [slurm_stats]

#ipa_cluster_deploy_ssh_keys_extra: []

# List of hw_scsi_models that result in block devices presenting as /dev/sdX
# rather than /dev/vdX
scsi_models:
  # Ceph [https://docs.ceph.com/en/quincy/rbd/rbd-openstack/#image-properties]
  - virtio-scsi
ipa_cluster_floating_ips_wanted: yes

ipa_cluster_allow_from_list:
  - "0.0.0.0/0":
    - ethertype: "IPv4"
      rule_suffix: "ssh_from_all"
      protocol: "tcp"
      port_range_min: "22"
      port_range_max: "22"
    - ethertype: "IPv4"
      protocol: "tcp"
      rule_suffix: "http_from_all"
      port_range_min: "80"
      port_range_max: "80"
    - ethertype: "IPv4"
      protocol: "tcp"
      rule_suffix: "https_from_all"
      port_range_min: "443"
      port_range_max: "443"
#disable insecure ldap by default as this is 0.0.0.0/0 this could be fine on a internal private network
#    - ethertype: "IPv4"
#      rule_suffix: "ldap_from_all"
#      protocol: "tcp"
#      port_range_min: "389"
#      port_range_max: "389"
    - ethertype: "IPv4"
      rule_suffix: "ldaps_from_all"
      protocol: "tcp"
      port_range_min: "636"
      port_range_max: "636"
    - ethertype: "IPv4"
      rule_suffix: "krbt88_from_all"
      protocol: "tcp"
      port_range_min: "88"
      port_range_max: "88"
    - ethertype: "IPv4"
      protocol: "tcp"
      rule_suffix: "krbt464_from_all"
      port_range_min: "464"
      port_range_max: "464"
    - ethertype: "IPv4"
      rule_suffix: "dnst_from_all"
      protocol: "tcp"
      port_range_min: "53"
      port_range_max: "53"
    - ethertype: "IPv4"
      protocol: "udp"
      rule_suffix: "dnsu_from_all"
      port_range_min: "53"
      port_range_max: "53"
    - ethertype: "IPv4"
      rule_suffix: "krbu88_from_all"
      protocol: "udp"
      port_range_min: "88"
      port_range_max: "88"
    - ethertype: "IPv4"
      rule_suffix: "krbu464_from_all"
      protocol: "udp"
      port_range_min: "464"
      port_range_max: "464"
# probably don't want to allow ntp from 0.0.0.0/0 but again this WOULD be required
#    - ethertype: "IPv4"
#      rule_suffix: "ntp_from_all"
#      protocol: "udp"
#      port_range_min: "123"
#      port_range_max: "123"
